server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      default-filters:
        - AddRequestHeader=source, agony
        - AddResponseHeader=source, agony-response
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**


dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848